### PR TITLE
MySQL / PostgreSQL support #33

### LINKED ISSUE #32: Cannot find datasource id in url api/tsdb/query
Hello guys,

I tried to set up your plugin following the [getting started guide](https://github.com/CorpGlory/grafana-data-exporter-panel/wiki), but after installing it Grafana returns an error for PostgreSQL datasource.

image

I set up and started Grafana for local development as explained [here](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md) and I followed all the steps in the installation guide.

> Installation
>     grafana-data-exporter for fetching data from Grafana datasources.
>     simple-json-datasource for progress tracking.
>     grafana-data-exporter-panel for exporting metrics from dashboard.
>     Import exporting template dashboard at http://<YOUR_GRAFANA_URL>/dashboard/import

What am I doing wrong? Should I use a specific version of Grafana?

Thank you in advance :)

### LINKED ISSUE #33: MySQL / PostgreSQL support
There is a "Cannot find datasource id in url api/tsdb/query" when a SQL datasource is used.

`grafana-data-exporter-panel` expects the datasource to have `/api/datasources/:id` proxy URL. SQL datasources' "Proxy URL" differs from other datasources: it has `/api/tsdb` proxy URL. 
We should support this case.

### PR DESCRIPTION
**Pull request by amper43**
## Problem
NoSQL datasources have `id` field in their `config.url` field.
SQL datasources don't have `id` field in `config.url`. All SQL queries are processed at `/api/tsdb` endpoint so datasource ID can be found only in response.

## Solution
In `ds-request-response` event callback we get datasource ID from `config.data.queries` field if it exists, otherwise ID is taken from `config.url`.

fixes #33 
fixes #32 

## Changes
- get `datasourceId` for SQL datasources from `config.data.queries` field

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -59,20 +59,35 @@ class Ctrl extends PanelCtrl {
...
-      let requestConfig = data.config;
-      let datasourceIdRegExp = requestConfig.url.match(/proxy\/(\d+)/);
-      if(datasourceIdRegExp === null) {
-        throw new Error(`Cannot find datasource id in url ${requestConfig.url}`);
+      const requestConfig = data.config;
+      const isSqlDatasource = requestConfig.data !== undefined &&
+        requestConfig.data.queries !== undefined;
+
+      if(isSqlDatasource) {
+
```
Comment (jonyrock-back) [inline src/module.ts]: remove this line

File: src/module.ts [hunk 2]
```diff
@@ -59,20 +59,35 @@ class Ctrl extends PanelCtrl {
...
+            data: query.data,
+            params: query.params
+          };
+        }
+      } else {
+        let matched = requestConfig.url.match(/proxy\/(\d+)/);
+        if(matched === null) {
+          throw new Error(`Cannot find datasource id in url ${requestConfig.url}`);
+        }
+
```
Comment (jonyrock-back) [inline src/module.ts]: remove this line

File: src/module.ts [hunk 3]
```diff
@@ -59,20 +59,35 @@ class Ctrl extends PanelCtrl {
...
+        let datasourceId = matched[1];
+
```
Comment (jonyrock-back) [inline src/module.ts]: remove this line
