### PR TITLE
Grafana 7: Missing default datasource #39

### LINKED ISSUE #39: Missing default datasource
Steps to reproduce: create a panel with prometheus query which selected as "default", like this:
image

and I will not appear in the grafana-data-exporter-panel list...

### PR DESCRIPTION
**Pull request by sblrok**
This PR fixes #39
**Probem:**

We don`t see default datasource in the exporter panel
**Solution:**

Send an additional request to get all datasources and find one with the isDefault = true
**Changes:**

Added _getDefaultDatasource functon
Changaed _getGrafanaAPIInfo function

### CODE REVIEW

File: src/module.ts [hunk 1]
```diff
@@ -175,12 +182,19 @@ class Ctrl extends PanelCtrl {
   private async _getGrafanaAPIInfo() {
     this._user = await this._getCurrentUser();
     for(let panel of this.panels) {
-      let datasourceName = panel.datasource;
-      if(!datasourceName) {
+      if(panel.type === 'corpglory-data-exporter-panel' || panel.datasource === undefined) {
```
Comment (jonyrock) [inline src/module.ts:185]: would nice to have a constant here for `'corpglory-data-exporter-panel'` here.

File: src/module.ts [hunk 2]
```diff
@@ -175,12 +182,19 @@ class Ctrl extends PanelCtrl {
...
         continue;
       }
-      let datasource = await this._getDatasourceByName(datasourceName);
-      this._datasourceTypes[panel.id] = datasource.type;
+
+      if(panel.datasource === null) {
+        const datasource = await this._getDefaultDatasource();
+        panel.datasource = datasource?.name;
+
```
Comment (jonyrock) [inline src/module.ts:192]: let's keep the code compact a bit :)

File: src/module.ts [hunk 3]
```diff
@@ -122,6 +122,13 @@ class Ctrl extends PanelCtrl {
     }
   }
 
+  // TODO: specify return type here
+  private async _getDefaultDatasource() {
+    const datasources = await this.backendSrv.get(`/api/datasources`);
+
```
Comment (jonyrock) [inline src/module.ts:128]: we don't need this empty line here :)
